import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Check, Download, FolderOpen, Link, LoaderCircle, Sparkles } from 'lucide-react';
import './style.css';

function App() {
  useEffect(() => { const bar = document.createElement('div'); bar.className = 'window-bar'; bar.innerHTML = '<div class="traffic-lights"><button class="traffic close" aria-label="Cerrar"></button><button class="traffic minimize" aria-label="Minimizar"></button><button class="traffic maximize" aria-label="Abrir releases"></button></div><span class="window-title">oWav</span>'; bar.querySelector('.close')?.addEventListener('click', () => window.electron.window.close()); bar.querySelector('.minimize')?.addEventListener('click', () => window.electron.window.minimize()); bar.querySelector('.maximize')?.addEventListener('click', () => window.electron.window.release()); document.body.prepend(bar); return () => bar.remove(); }, []);
  const [url, setUrl] = useState(''); const [info, setInfo] = useState<VideoInfo | null>(null); const [busy, setBusy] = useState(false); const [analyzing, setAnalyzing] = useState(false); const [error, setError] = useState(''); const [progress, setProgress] = useState({ percent: 0, status: '' }); const [saved, setSaved] = useState('');
  useEffect(() => window.electron.youtube.onProgress(setProgress), []);
  useEffect(() => { const field = document.querySelector('.input'); const icon = field?.querySelector('svg'); if (!field || !icon) return; field.classList.toggle('is-busy', busy); icon.classList.add('clear-link'); icon.classList.toggle('download-bounce', busy); icon.classList.toggle('is-locked', busy); icon.setAttribute('title', busy ? 'Descarga en curso' : 'Borrar enlace'); if (busy) { icon.innerHTML = '<path d="M12 15V3"/><path d="m7 10 5 5 5-5"/><path d="M5 21h14"/>'; return; } icon.innerHTML = '<path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/>'; const clear = () => setUrl(''); icon.addEventListener('click', clear); return () => icon.removeEventListener('click', clear); }, [url, busy]);
  useEffect(() => { const value = url.trim(); setInfo(null); setSaved(''); setError(''); if (!value) return; const timer = window.setTimeout(async () => { setAnalyzing(true); try { setInfo(await window.electron.youtube.getInfo(value)); } catch (e) { setError(e instanceof Error ? e.message : 'No pudimos obtener la información del video.'); } finally { setAnalyzing(false); } }, 550); return () => window.clearTimeout(timer); }, [url]);
  const download = async () => { if (!info) return; const outputPath = await window.electron.file.choosePath(`${info.title.replace(/[\\/:*?"<>|]/g, '_')}.wav`); if (!outputPath) return; setBusy(true); setSaved(''); setError(''); try { await window.electron.youtube.download({ url, outputPath }); setSaved(outputPath); } catch (e) { setError(e instanceof Error ? e.message : 'No pudimos descargar este audio.'); } finally { setBusy(false); } };
  return <main><div className="ambient ambient-one" /><div className="ambient ambient-two" /><header><div className="app-mark"><Sparkles size={18} /></div><div><h1>Wave</h1><p>Audio, hecho simple.</p></div><div className="live-dot" /></header><section className="hero"><span className="eyebrow">YOUTUBE <i>→</i> WAV</span><h2>Tu audio,<br /><em>en su mejor forma.</em></h2><p className="intro">Pega un enlace y lo convertiremos en un archivo WAV de alta calidad.</p></section><section className="search"><div className={`input ${analyzing ? 'is-loading' : ''}`}><Link size={17} /><input value={url} onChange={e => setUrl(e.target.value)} placeholder="Pega un enlace de YouTube" aria-label="Enlace de YouTube" />{analyzing && <LoaderCircle className="spin" size={16} />}</div>{error && <div className="error">{error}</div>}</section>{info && <section className="preview"><img src={info.thumbnail} /><div className="preview-copy"><span className="label">VIDEO LISTO</span><h3>{info.title}</h3><p>{info.channel}<b>·</b>{info.duration}</p></div><Check className="preview-check" size={18} /></section>}{busy && <section className="progress"><div className="row"><span>{progress.status || 'Preparando'}</span><b>{Math.round(progress.percent)}%</b></div><div className="bar"><i style={{ width: `${progress.percent}%` }} /></div></section>}{saved && !busy ? <section className="done"><Check /><div><strong>Tu archivo está listo</strong><span>{saved.split(/[\\/]/).pop()}</span></div><button onClick={() => window.electron.file.showInFolder(saved)}><FolderOpen size={15} />Abrir carpeta</button></section> : <button className="download" onClick={download} disabled={!info || busy || analyzing}>{busy ? <LoaderCircle className="spin" /> : <Download size={18} />}{busy ? 'Preparando tu WAV…' : 'Descargar WAV'}<span>⌘</span></button>}<footer><span className="lock">⌁</span> Procesamiento local · Sin cuentas · Sin historial</footer></main>;
}
createRoot(document.getElementById('root')!).render(<App />);
