import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Check, Download, FolderOpen, Link, LoaderCircle, Sparkles } from 'lucide-react';
import './style.css';

function App() {
  const [url, setUrl] = useState(''); const [info, setInfo] = useState<VideoInfo | null>(null); const [busy, setBusy] = useState(false); const [analyzing, setAnalyzing] = useState(false); const [error, setError] = useState(''); const [progress, setProgress] = useState({ percent: 0, status: '' }); const [saved, setSaved] = useState('');
  useEffect(() => window.electron.youtube.onProgress(setProgress), []);
  useEffect(() => { const icon = document.querySelector('.input > svg'); if (!icon) return; icon.classList.add('clear-link'); icon.setAttribute('title', 'Borrar enlace'); const clear = () => setUrl(''); icon.addEventListener('click', clear); return () => icon.removeEventListener('click', clear); }, [url]);
  useEffect(() => { const value = url.trim(); setInfo(null); setSaved(''); setError(''); if (!value) return; const timer = window.setTimeout(async () => { setAnalyzing(true); try { setInfo(await window.electron.youtube.getInfo(value)); } catch (e) { setError(e instanceof Error ? e.message : 'No pudimos obtener la información del video.'); } finally { setAnalyzing(false); } }, 550); return () => window.clearTimeout(timer); }, [url]);
  const download = async () => { if (!info) return; const outputPath = await window.electron.file.choosePath(`${info.title.replace(/[\\/:*?"<>|]/g, '_')}.wav`); if (!outputPath) return; setBusy(true); setSaved(''); setError(''); try { await window.electron.youtube.download({ url, outputPath }); setSaved(outputPath); } catch (e) { setError(e instanceof Error ? e.message : 'No pudimos descargar este audio.'); } finally { setBusy(false); } };
  return <main><div className="ambient ambient-one" /><div className="ambient ambient-two" /><header><div className="app-mark"><Sparkles size={18} /></div><div><h1>Wave</h1><p>Audio, hecho simple.</p></div><div className="live-dot" /></header><section className="hero"><span className="eyebrow">YOUTUBE <i>→</i> WAV</span><h2>Tu audio,<br /><em>en su mejor forma.</em></h2><p className="intro">Pega un enlace y lo convertiremos en un archivo WAV de alta calidad.</p></section><section className="search"><div className={`input ${analyzing ? 'is-loading' : ''}`}><Link size={17} /><input value={url} onChange={e => setUrl(e.target.value)} placeholder="Pega un enlace de YouTube" aria-label="Enlace de YouTube" />{analyzing && <LoaderCircle className="spin" size={16} />}</div>{error && <div className="error">{error}</div>}</section>{info && <section className="preview"><img src={info.thumbnail} /><div className="preview-copy"><span className="label">VIDEO LISTO</span><h3>{info.title}</h3><p>{info.channel}<b>·</b>{info.duration}</p></div><Check className="preview-check" size={18} /></section>}{busy && <section className="progress"><div className="row"><span>{progress.status || 'Preparando'}</span><b>{Math.round(progress.percent)}%</b></div><div className="bar"><i style={{ width: `${progress.percent}%` }} /></div></section>}{saved && !busy ? <section className="done"><Check /><div><strong>Tu archivo está listo</strong><span>{saved.split(/[\\/]/).pop()}</span></div><button onClick={() => window.electron.file.showInFolder(saved)}><FolderOpen size={15} />Abrir carpeta</button></section> : <button className="download" onClick={download} disabled={!info || busy || analyzing}>{busy ? <LoaderCircle className="spin" /> : <Download size={18} />}{busy ? 'Preparando tu WAV…' : 'Descargar WAV'}<span>⌘</span></button>}<footer><span className="lock">⌁</span> Procesamiento local · Sin cuentas · Sin historial</footer></main>;
}
createRoot(document.getElementById('root')!).render(<App />);
